export const items = [
  {
    name: 'klik',
    keys: 'klik',
    description: 'Lorem ipsum ',
    media: '.',
    category: 'Horní část těla',
    id: 0,
  },
  {
    name: 'přítahy',
    keys: 'pritahy',
    description: 'Lorem ipsum ',
    media: '.',
    category: 'Horní část těla',
    id: 0,
  },
  {
    name: 'dřep',
    keys: 'dřep',
    description: 'Lorem ipsum ',
    media: '.',
    category: 'Dolní část těla',
    id: 1,
  },
  {
    name: 'výpady',
    keys: 'výpady',
    description: 'Lorem ipsum ',
    media: '.',
    category: 'Dolní část těla',
    id: 1,
  },
  {
    name: 'švihadlo',
    keys: 'švihadlo',
    description: 'Lorem ipsum ',
    media: '.',
    category: 'cardio',
    id: 2,
  },
  {
    name: 'angličák',
    keys: 'angličák',
    description: 'Lorem ipsum ',
    media: '.',
    category: 'cardio',
    id: 2,
  },
];
